### ISSUE TITLE
Respect `spring-data-aerospike` `writeSortedMaps` property

### ISSUE THREAD

**Issue by Ferioney** [aerospike-community/spring-data-aerospike-starters#260]
In `spring-data-aerospike:4.8.0` was added property `writeSortedMaps` which allows to disable writing Maps as sorted trees (see [documentation page](https://aerospike.github.io/spring-data-aerospike/) and related issue [NullPointer exception when overriding AerospikeTypeAliasAccessor(null) after update to 4.7.1](https://github.com/aerospike/spring-data-aerospike/issues/743) ). 

Please add support of property `writeSortedMaps` to `spring-data-aerospike-starters`

**Comment by agrgr** [comment]
Starters version 0.16.1 with `writeSortedMaps` property is released
