### ISSUE TITLE
Allow configuration of the typeKey for AerospikeTypeAliasAccessor

### ISSUE THREAD

**Issue by andrei-ivanov** [aerospike-community/spring-data-aerospike-starters#262]
The `spring.data.aerospike.type-key` property is deprecated (well, the whole `AerospikeDataProperties` is actually deprecated), but I couldn't find a replacement for configuring the `typeKey` of `AerospikeTypeAliasAccessor` (to set it to `null` actually)

Please add one.

Thank you! ☺

**Comment by agrgr** [comment]
Hi @andrei-ivanov!

Version 0.15 contained deprecated configuration properties in anticipation to some changes that were cancelled after getting feedback about necessity to keep properties names the same.
Please use the version 0.16, it contains un-deprecated properties.

**Comment by andrei-ivanov** [comment]
Seems fine, thanks
