### ISSUE TITLE
Unable to download artifact from maven central

### ISSUE THREAD

**Issue by lfarmer** [aerospike-community/spring-data-aerospike-starters#69]
Hi,

I've attempted to add the following to the `pom.xml`

```xml
<dependency>
  <groupId>com.aerospike</groupId>
  <artifactId>spring-boot-starter-data-aerospike</artifactId>
  <version>0.5.0</version>
</dependency>
```

But get the following error `Could not transfer artifact com.aerospike-data-aerospike-starters:pom:${revision} from/to central`  

Not sure if this is the reason, but the [pom](https://repo1.maven.org/maven2/com/aerospike/spring-boot-starter-data-aerospike/0.5.0/spring-boot-starter-data-aerospike-0.5.0.pom) seems to contain `${revision}` within the version.

**Comment by roimenashe** [comment]
@lfarmer Thanks for noticing.
Added a linked pull request that should solve this issue, a fix will be included in the next version hopefully very soon.

**Comment by roimenashe** [comment]
@lfarmer Version 0.6.0 is now available on Maven Central - try it out and please let us know if everything works properly now.

**Comment by lfarmer** [comment]
Hi @roimenashe,  I confirm I can now access version 0.6.0 from maven central.  Thanks for sorting 👍
